### ISSUE TITLE
The following error occurs under certain conditions

### ISSUE THREAD

**Issue by otofuserver** [AirplanegoBrr/BlockBreaker-BlockPlacer#5]
spigot1.19.3

hello
The following error occurs under certain conditions
May appear with a stone making machine with built-in block breaker.
Some stone makers make errors and some don't.

[2023/01/28/02:35:28] [Server thread/ERROR]: Could not pass event BlockDispenseEvent to Blockbreakerblockplacer v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.core.dispenser.DispenseBehaviorItem.spawnItem(DispenseBehaviorItem.java:77) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.core.dispenser.DispenseBehaviorItem.a(DispenseBehaviorItem.java:44) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.core.dispenser.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:31) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.world.level.block.BlockDropper.a(BlockDropper.java:59) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.world.level.block.BlockDispenser.a(BlockDispenser.java:121) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:963) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.level.WorldServer.d(WorldServer.java:825) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.world.ticks.TickListServer.a(SourceFile:215) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.world.ticks.TickListServer.a(SourceFile:98) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:370) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1294) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1201) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3619-Spigot-d90018e-6459934]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.CraftDropper cannot be cast to class org.bukkit.block.Dispenser (org.bukkit.craftbukkit.v1_19_R2.block.CraftDropper and org.bukkit.block.Dispenser are in unnamed module of loader java.net.URLClassLoader @31221be2)
        at com.airplanegobrr.blockbreakerblockplacer.events.onBlockDispense.BlockDispenseEvent(onBlockDispense.java:31) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 19 more

**Comment by otofuserver** [comment]
I planted markers in suspicious places.

       // blockbreaker
        if (bbEnabled) {
            if (debug) {
                main.getLogger().info(item.toString());
                main.getLogger().info(item.getType().toString());
                main.getLogger().info(item.getType().name());
                main.getLogger().info(xyzName);
            }

            if (item.getType().toString().contains("PICKAXE")) {
                //main.getLogger().info("Pickaxe detected!");
                main.getLogger().info("test1");
                BlockFace bsFace = ((Directional) block.getBlockData()).getFacing();
                main.getLogger().info("test2");
                Block bsBlock = block.getRelative(bsFace);
                main.getLogger().info("test3");
                Material bsMaterial = bsBlock.getType();
                main.getLogger().info("test4");
                // if the material is not bedrock then break it
                if (bsMaterial != Material.BEDROCK) {
                    main.getLogger().info("test5");
                    bsBlock.breakNaturally();
                    main.getLogger().info("test6");
                    event.setCancelled(true);
                }
            }
        }

[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test1
[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test2
[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test3
[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test4
[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test5
[2023/01/28/02:53:19] [Server thread/INFO]: [Blockbreakerblockplacer] test6
[2023/01/28/02:53:19] [Server thread/ERROR]: Could not pass event BlockDispenseEvent to Blockbreakerblockplacer v1.0
org.bukkit.event.EventException: null

**Comment by AirplanegoBrr** [comment]
mhh I would just wrap `event.setCancelled(true);` in a try block.
I think this is a threading issue or maybe your firing events too fast
